
riverswim_6:
  entrypoint: "riverswim:RiverSwim"
  kwargs:
    nbStates: 6


ergoriverwsim_6:
  entrypoint: "riverswim:ErgodicRiverSwim"
  kwargs:
    nbStates: 6
    ergodic: 0.001



randomS10A3:
  entrypoint: "randomMDP:RandomMDP"
  displayname: "Random MDP S=10, A=3"
  kwargs:
    nbStates: 10
    nbActions: 3
    rewardStd: 0.5


randomdetRS10A3:
  entrypoint: "randomMDP:RandomMDP"
  displayname: "Random MDP  S=10, A=3 (deterministic rewards)"
  kwargs:
    nbStates: 10
    nbActions: 3
    rewardStd: 0


randomS50A3:
  entrypoint: "randomMDP:RandomMDP"
  displayname: "Random MDP S=50, A=3"
  kwargs:
    nbStates: 50
    nbActions: 3
    rewardStd: 0.5