
grid-random-1616:
  entrypoint: "gridworlds:GridWorld"
  displayname: "Random GridWorld map 16x16 states"
  kwargs:
    map_name: "random"
    sizeX: 16
    sizeY: 16
    initialSingleStateDistribution: False
    density: 0.4
    lengthofwalks: 5
    nbGoals: 1
    rewardStd: 0.01
    seed: 7

grid-random-1212:
  entrypoint: "gridworlds:GridWorld"
  displayname: "Random GridWorld map 12x12 states"
  kwargs:
    map_name: "random"
    sizeX: 12
    sizeY: 12
    initialSingleStateDistribution: False
    density: 0.4
    lengthofwalks: 5
    nbGoals: 1
    rewardStd: 0.01
    seed: 5

grid-random-88:
  entrypoint: "gridworlds:GridWorld"
  displayname: "Random GridWorld map 8x8 states"
  kwargs:
    map_name: "random"
    sizeX: 8
    sizeY: 8
    initialSingleStateDistribution: False
    density: 0.4
    lengthofwalks: 5
    nbGoals: 1
    rewardStd: 0.01
    seed: 1 #,#16 16 7# 12 12 5 # 8 8 1

grid-2-room:
  entrypoint: "gridworlds:GridWorld"
  displayname: "2-room gridworld 9x11 states"
  kwargs:
    sizeX: 9
    sizeY: 11
    map_name: "2-room"
    initialSingleStateDistribution: True
    start: [1,1]
    nbGoals: 1
    goal: [7,9]
    rewardStd: 0.0
    seed: 1

grid-4-room:
  entrypoint: "gridworlds:GridWorld"
  displayname: "4-room gridworld 9x11 states"
  kwargs:
    sizeX: 7
    sizeY: 7
    map_name: "4-room"
    initialSingleStateDistribution: True
    start: [1,1]
    nbGoals: 1
    goal: [5,5]
    rewardStd: 0.0
    seed: 1
    slippery: 0.1
